services:
  postgres:
    restart: always
    ports: []

  app-blue:
    image: TU_USUARIO/sportsclub:latest
    restart: always
    
  app-green:
    image: TU_USUARIO/sportsclub:latest
    restart: always

  nginx:
    restart: always
    ports:
      - "80:80"